# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francisco Lopez Lasanta
email: flopezlasanta@gmail.com
description: Just another tech blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flopezlasanta.github.io" # the base hostname & protocol for your site
github_username:    flopezlasanta
linkedin_username:  flopezlasanta
keybase_username:   flopezlasanta

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-gist]
